version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.14
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/static:/opt/jirarush/resources/static:ro
    depends_on:
      - jira
    restart: always
